import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { createClient } from "../../utils/supabase/server";

const inter = Inter({ subsets: ["latin"] });
const supabase = createClient()
 
  const {
    data: { user },
  } = await supabase.auth.getUser()

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar user={user} />
        {children}
        </body>
    </html>
  );
}
